Adds to_excel
newsela/pandas_ext pull request #23
Opened 2019-03-22 21:47 UTC by richiverse

2019-03-22 21:49 UTC, WilliamBurdett approved these changes

2019-03-25 15:09 UTC, lukeorland requested changes
I tried to use this and got `ModuleNotFoundError: No module named 'openpyxl'`

2019-03-25 15:09 UTC, lukeorland commented on pandas_ext/excel.py
> +from os import path, remove
I prefer to just `import os`, then it's clear within the module what `path` and `remove` are, because `os.path.join()` and `os.remove()` are being called explicitly.

2019-03-25 15:09 UTC, lukeorland commented on pandas_ext/excel.py
> +        remove(tmp_file)
1. We should use a context manager for the read as well, I think.
2. Is this `os.remove` statement ever reached, since `return` was already called? 

suggestion: 

```python
        with open(tmp_file, 'rb') as source, s3.open(file_path, 'wb') as dest:
            dest.write(source.read())
        remove(tmp_file)
        return
```

2019-03-25 15:09 UTC, lukeorland commented on pandas_ext/excel.py
> +        # writer.save()
This line can be deleted for cleaner code, correct?

2019-03-29 12:46 UTC, richiverse commented
@lukeorland by default this will use xlwt for xls or xlsxwriter for xlsx but you can override by specifying `engine`. If not specified it will be auto-determined based on the files extension.

I prefer xlsxwriter over openpyxl for formatting and speed but you're welcome to update the engine as needed.

2019-03-29 12:47 UTC, merged